**Archivo: `.streamlit/config.toml`** (crear carpeta `.streamlit` primero)
```toml
[theme]
primaryColor = "#3B82F6"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F9FAFB"
textColor = "#111827"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
